/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import java.util.regex.*;
import javax.swing.JOptionPane;
/**
 *
 * @author bharatsingh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Submission_Dialog_Box = new javax.swing.JDialog();
        ButtonCheck = new javax.swing.ButtonGroup();
        Swing_Assignment = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        First_Name_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        First_Name_Input = new javax.swing.JTextField();
        Submit_Button = new javax.swing.JButton();
        Last_Name_Input = new javax.swing.JTextField();
        Email_Input = new javax.swing.JTextField();
        Last_Name_Label = new javax.swing.JLabel();
        Age_Label = new javax.swing.JLabel();
        First_Name_Validation = new javax.swing.JLabel();
        Last_Name_Validation = new javax.swing.JLabel();
        Age_Validation = new javax.swing.JLabel();
        Email_Validation = new javax.swing.JLabel();
        Message_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Message_Input = new javax.swing.JTextArea();
        Check1 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout Submission_Dialog_BoxLayout = new javax.swing.GroupLayout(Submission_Dialog_Box.getContentPane());
        Submission_Dialog_Box.getContentPane().setLayout(Submission_Dialog_BoxLayout);
        Submission_Dialog_BoxLayout.setHorizontalGroup(
            Submission_Dialog_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Submission_Dialog_BoxLayout.setVerticalGroup(
            Submission_Dialog_BoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 51, 51));
        setFont(new java.awt.Font("Arial Unicode MS", 3, 36)); // NOI18N

        Swing_Assignment.setBackground(new java.awt.Color(204, 255, 204));

        Title_Label.setFont(new java.awt.Font("Kohinoor Bangla", 3, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(51, 51, 255));
        Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Label.setText("Customer Registration Form");

        First_Name_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        First_Name_Label.setText("First Name");

        Email_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Email_Label.setText("Email");

        First_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_Name_InputActionPerformed(evt);
            }
        });
        First_Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyTyped(evt);
            }
        });

        Submit_Button.setText("Submit");
        Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_ButtonActionPerformed(evt);
            }
        });

        Last_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_Name_InputActionPerformed(evt);
            }
        });
        Last_Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Last_Name_InputKeyReleased(evt);
            }
        });

        Email_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Email_InputKeyReleased(evt);
            }
        });

        Last_Name_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Last_Name_Label.setText("Last Name");

        Age_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Age_Label.setText("Age");

        First_Name_Validation.setBackground(new java.awt.Color(255, 255, 0));
        First_Name_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        First_Name_Validation.setForeground(new java.awt.Color(255, 0, 0));

        Last_Name_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        Last_Name_Validation.setForeground(new java.awt.Color(255, 0, 0));

        Age_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        Age_Validation.setForeground(new java.awt.Color(255, 0, 0));

        Email_Validation.setFont(new java.awt.Font("Helvetica Neue", 3, 13)); // NOI18N
        Email_Validation.setForeground(new java.awt.Color(255, 0, 0));

        Message_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Message_Label.setText("Message");

        Message_Input.setColumns(20);
        Message_Input.setRows(5);
        Message_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Message_InputKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Message_Input);

        ButtonCheck.add(Check1);
        Check1.setText("Check1");
        Check1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check1ActionPerformed(evt);
            }
        });

        ButtonCheck.add(jRadioButton1);
        jRadioButton1.setText("Check2");

        javax.swing.GroupLayout Swing_AssignmentLayout = new javax.swing.GroupLayout(Swing_Assignment);
        Swing_Assignment.setLayout(Swing_AssignmentLayout);
        Swing_AssignmentLayout.setHorizontalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(First_Name_Label)
                                    .addComponent(Email_Label)
                                    .addComponent(Last_Name_Label)
                                    .addComponent(Age_Label)
                                    .addComponent(Message_Label))
                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Email_Validation))
                                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(First_Name_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                                    .addComponent(Last_Name_Input))
                                                .addGap(50, 50, 50)
                                                .addComponent(Last_Name_Validation))
                                            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                                .addGap(188, 188, 188)
                                                .addComponent(Check1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(First_Name_Validation)
                                            .addComponent(Age_Validation)))
                                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                                        .addGap(175, 175, 175)
                                        .addComponent(Email_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(6, 6, 6)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        Swing_AssignmentLayout.setVerticalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(First_Name_Validation))
                .addGap(5, 5, 5)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Last_Name_Label)
                    .addComponent(Last_Name_Validation))
                .addGap(2, 2, 2)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_Label)
                    .addComponent(Age_Validation)
                    .addComponent(Check1)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Email_Label)
                    .addComponent(Email_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(Email_Validation)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Message_Label))
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(Submit_Button)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        Check1.getAccessibleContext().setAccessibleDescription("Check1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Swing_Assignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Swing_Assignment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void First_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        
        String Fname=First_Name_Input.getText();
        String Lname=Last_Name_Input.getText();
        String Age= ButtonCheck.getSelection().getActionCommand().toString();
        String Email=Email_Input.getText().toString();
        String Message=Message_Input.getText().toString();
       if(First_Name_Validation.getText()==null)
       {
           if(Last_Name_Validation.getText()==null)
           {
               if(Age_Validation.getText()==null)
               {
                   if(Email_Validation.getText()==null)
                   {
                       JOptionPane.showMessageDialog(this,"First Name is "+Fname+". "+"Last Name is "+Lname+". "+"Age is "+Age+". "+"Email is "+Email+" And the message is "+Message , "User Validation Complete", HEIGHT);
                   }
                   else{JOptionPane.showMessageDialog(this, "Please enter valid details", "Error", HEIGHT);}
               }
               else{JOptionPane.showMessageDialog(this, "Please enter valid details", "Error", HEIGHT);}
           }
           else{JOptionPane.showMessageDialog(this, "Please enter valid details", "Error", HEIGHT);}
       }
       else{JOptionPane.showMessageDialog(this, "Please enter valid details", "Error", HEIGHT);}
       
       System.out.println(Age);
        
       
        
    }                                             

    private void Last_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void First_Name_InputKeyTyped(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        //String valid_str= "^[a-zA-z]$";
        
    }                                         

    private void First_Name_InputKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
        Pattern pattern=Pattern.compile("^[a-zA-Z+ ]{1,30}$");
        Matcher matcher=pattern.matcher(First_Name_Input.getText());
        boolean Validation =matcher.find();
        if (!Validation){First_Name_Validation.setText("First name Invalid");}
        else{First_Name_Validation.setText(null);}
    }                                            

    private void Last_Name_InputKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        Pattern pattern=Pattern.compile("^[a-zA-Z+ ]{1,30}$");
        Matcher matcher=pattern.matcher(Last_Name_Input.getText());
        boolean Validation =matcher.find();
        if (!Validation){Last_Name_Validation.setText("Last name Invalid");}
        else{Last_Name_Validation.setText(null);}
    }                                           

    private void Email_InputKeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
        String regex="^[A-Za-z0-9+._-]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z]{0,10}$";
        Pattern pattern=Pattern.compile(regex);
        Matcher matcher=pattern.matcher((Email_Input.getText()));
        //boolean Validation =matcher.matches();
        if (!matcher.matches()){Email_Validation.setText("Invalid email");}
        else{Email_Validation.setText(null);}
    }                                       

    private void Message_InputKeyReleased(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Check1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Age_Label;
    private javax.swing.JLabel Age_Validation;
    private javax.swing.ButtonGroup ButtonCheck;
    private javax.swing.JRadioButton Check1;
    private javax.swing.JTextField Email_Input;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JLabel Email_Validation;
    private javax.swing.JTextField First_Name_Input;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JLabel First_Name_Validation;
    private javax.swing.JTextField Last_Name_Input;
    private javax.swing.JLabel Last_Name_Label;
    private javax.swing.JLabel Last_Name_Validation;
    private javax.swing.JTextArea Message_Input;
    private javax.swing.JLabel Message_Label;
    private javax.swing.JDialog Submission_Dialog_Box;
    private javax.swing.JButton Submit_Button;
    private javax.swing.JPanel Swing_Assignment;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
