/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.User;
import javax.swing.JPanel;

/**
 *
 * @author bharatsingh
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */
     //private JPanel BottomPanel; 
    public ViewPanel(User NewUser) {
        initComponents();
        First_Name_Input.setText(NewUser.getFirstName());
        Last_Name_Input.setText(NewUser.getLastName());
        Age_Input.setText(NewUser.getAge());
        Email_Input.setText(NewUser.getEmail());
        GenderOutput.setText(NewUser.getGender());
        Patient_Type_Output.setText(NewUser.getPatientType());
        Message_Input.setText(NewUser.getMessage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Swing_Assignment = new javax.swing.JPanel();
        Title_Label = new javax.swing.JLabel();
        First_Name_Label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        First_Name_Input = new javax.swing.JTextField();
        Last_Name_Input = new javax.swing.JTextField();
        Age_Input = new javax.swing.JTextField();
        Email_Input = new javax.swing.JTextField();
        Last_Name_Label = new javax.swing.JLabel();
        Age_Label = new javax.swing.JLabel();
        Message_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Message_Input = new javax.swing.JTextArea();
        Gender_Label = new javax.swing.JLabel();
        Patient_Type_Label = new javax.swing.JLabel();
        Patient_Type_Output = new javax.swing.JTextField();
        GenderOutput = new javax.swing.JTextField();

        Swing_Assignment.setBackground(new java.awt.Color(204, 255, 204));

        Title_Label.setFont(new java.awt.Font("Kohinoor Bangla", 3, 36)); // NOI18N
        Title_Label.setForeground(new java.awt.Color(51, 51, 255));
        Title_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_Label.setText("Patient View");

        First_Name_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        First_Name_Label.setText("First Name");

        Email_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Email_Label.setText("Email");

        First_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                First_Name_InputActionPerformed(evt);
            }
        });
        First_Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                First_Name_InputKeyTyped(evt);
            }
        });

        Last_Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Last_Name_InputActionPerformed(evt);
            }
        });
        Last_Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Last_Name_InputKeyReleased(evt);
            }
        });

        Age_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_InputActionPerformed(evt);
            }
        });
        Age_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Age_InputKeyReleased(evt);
            }
        });

        Email_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Email_InputKeyReleased(evt);
            }
        });

        Last_Name_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Last_Name_Label.setText("Last Name");

        Age_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Age_Label.setText("Age");

        Message_Label.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Message_Label.setText("Message");

        Message_Input.setColumns(20);
        Message_Input.setRows(5);
        Message_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Message_InputKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(Message_Input);

        Gender_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Gender_Label.setText("Gender");

        Patient_Type_Label.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Patient_Type_Label.setText("Patient Type");

        Patient_Type_Output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Patient_Type_OutputActionPerformed(evt);
            }
        });

        GenderOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderOutputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Swing_AssignmentLayout = new javax.swing.GroupLayout(Swing_Assignment);
        Swing_Assignment.setLayout(Swing_AssignmentLayout);
        Swing_AssignmentLayout.setHorizontalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(First_Name_Label)
                            .addComponent(Email_Label)
                            .addComponent(Last_Name_Label)
                            .addComponent(Age_Label)
                            .addComponent(Message_Label)
                            .addComponent(Gender_Label)
                            .addComponent(Patient_Type_Label))
                        .addGap(64, 64, 64)
                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(First_Name_Input, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(Last_Name_Input)
                                .addComponent(Age_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Email_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Patient_Type_Output, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        Swing_AssignmentLayout.setVerticalGroup(
            Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First_Name_Label)
                    .addComponent(First_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Last_Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Last_Name_Label))
                .addGap(5, 5, 5)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Age_Label))
                .addGap(4, 4, 4)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email_Label)
                    .addComponent(Email_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender_Label)
                    .addComponent(GenderOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addComponent(Patient_Type_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(Swing_AssignmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Message_Label)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(Swing_AssignmentLayout.createSequentialGroup()
                        .addComponent(Patient_Type_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Swing_Assignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Swing_Assignment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void First_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void First_Name_InputKeyReleased(java.awt.event.KeyEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void First_Name_InputKeyTyped(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
        //String valid_str= "^[a-zA-z]$";
    }                                         

    private void Last_Name_InputActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void Last_Name_InputKeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void Age_InputActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void Age_InputKeyReleased(java.awt.event.KeyEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void Email_InputKeyReleased(java.awt.event.KeyEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void Patient_Type_OutputActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void GenderOutputActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void Message_InputKeyReleased(java.awt.event.KeyEvent evt) {                                          
        // TODO add your handling code here:
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JTextField Age_Input;
    private javax.swing.JLabel Age_Label;
    private javax.swing.JTextField Email_Input;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JTextField First_Name_Input;
    private javax.swing.JLabel First_Name_Label;
    private javax.swing.JTextField GenderOutput;
    private javax.swing.JLabel Gender_Label;
    private javax.swing.JTextField Last_Name_Input;
    private javax.swing.JLabel Last_Name_Label;
    private javax.swing.JTextArea Message_Input;
    private javax.swing.JLabel Message_Label;
    private javax.swing.JLabel Patient_Type_Label;
    private javax.swing.JTextField Patient_Type_Output;
    private javax.swing.JPanel Swing_Assignment;
    private javax.swing.JLabel Title_Label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
